#!/bin/bash

. env.sh

docker stop -t 10 ${NAME}wordpress
docker rm -fv ${NAME}wordpress

docker run --name ${NAME}wordpress -d \
    --volumes-from ${NAME}wordpress-volume \
    -e WORDPRESS_DB_HOST=${NAME}wordpress-mariadb \
    -e WORDPRESS_DB_USER=$MYSQL_USER \
    -e WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD \
    -e WORDPRESS_DB_NAME=$MUSQL_USER \
    -e WORDPRESS_AUTH_KEY=$WORDPRESS_AUTH_KEY \
    -e WORDPRESS_SECURE_AUTH_KEY=$WORDPRESS_SECURE_AUTH_KEY \
    -e WORDPRESS_LOGGED_IN_KEY=$WORDPRESS_LOGGED_IN_KEY \
    -e WORDPRESS_NONCE_KEY=$WORDPRESS_NONCE_KEY \
    -e WORDPRESS_AUTH_SALT=$WORDPRESS_AUTH_SALT \
    -e WORDPRESS_SECURE_AUTH_SALT=$WORDPRESS_SECURE_AUTH_SALT \
    -e WORDPRESS_LOGGED_IN_SALT=$WORDPRESS_LOGGED_IN_SALT \
    -e WORDPRESS_NONCE_SALT=$WORDPRESS_NONCE_SALT \
    --restart always \
    wordpress
